- name: user set up 
  hosts: user
  become: yes

  tasks:
  - name: disabling and enabling nodejs
    ansible.builtin.shell: dnf module disable nodejs -y && dnf module enable nodejs:20 -y

    
  - name: installing nodejs 
    ansible.builtin.package:
      name: nodejs
      state: present
  
  - name: adding application user
    ansible.builtin.user:
      name: roboshop
      state: present
      system: true
      shell: /sbin/nologin
      home: /app
      # Safe to remove directory, because 2nd time if we run it will download freshly. no error if does not exist
  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creating app directory
    ansible.builtin.file:
      state: directory
      path:  /app

  - name: Delete user file
    ansible.builtin.file:
      path: /tmp/user.zip
      state: absent

  - name: downloading the user files
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip

  - name: unzipping the files
    ansible.builtin.unarchive:
      src: /tmp/user.zip 
      dest: /app
      remote_src: yes
  
  - name: installing dependences
    community.general.npm:
      path: /app

  - name: copying the service file to systemd
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: daemon reload enable and start
    ansible.builtin.systemd_service:
      name: user
      enabled: true
      state: started
      daemon_reload: true
  