- name: user set up 
  hosts: user
  become: yes

  tasks:
  - name: disabling and enabling nodejs
    ansible.builtin.command: dnf module disable nodejs -y 
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: installing nodejs 
    ansible.builtin.package:
      name: nodejs
      state: present
  
  - name: adding application user
    ansible.builtin.user:
      name: roboshop
      state: present
      system: true
      shell: /sbin/nologin
      home: /app

  - name: creating app directory
    ansible.builtin.file:
      state: directory
      path:  /app

  - name: downloading the user files
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip

  - name: unzipping the files
    ansible.builtin.unarchive:
      src: /tmp/user.zip 
      dest: /app
      remote_src: yes
  
  - name: installing dependences
    community.general.npm:
      path: /app

  - name: copying the service file to systemd
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: reload deamon
    ansible.builtin.systemd_service:
      daemon_reload: true